/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: descriptor.proto */

#ifndef PROTOBUF_C_descriptor_2eproto__INCLUDED
#define PROTOBUF_C_descriptor_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Blizzard__Descriptor__Descriptor Blizzard__Descriptor__Descriptor;
typedef struct Blizzard__Descriptor__List Blizzard__Descriptor__List;
typedef struct Blizzard__Descriptor__Object Blizzard__Descriptor__Object;
typedef struct Blizzard__Descriptor__Object__PropertiesEntry Blizzard__Descriptor__Object__PropertiesEntry;
typedef struct Blizzard__Descriptor__Optional Blizzard__Descriptor__Optional;


/* --- enums --- */

typedef enum _Blizzard__Descriptor__BasicTypes {
  BLIZZARD__DESCRIPTOR__BASIC_TYPES__BOOLEAN = 0,
  BLIZZARD__DESCRIPTOR__BASIC_TYPES__INTEGER = 1,
  BLIZZARD__DESCRIPTOR__BASIC_TYPES__DOUBLE = 2,
  BLIZZARD__DESCRIPTOR__BASIC_TYPES__STRING = 3,
  BLIZZARD__DESCRIPTOR__BASIC_TYPES__BYTES = 4,
  /*
   * Represents any type, used for dynamic or unknown types
   */
  BLIZZARD__DESCRIPTOR__BASIC_TYPES__ANY = 5,
  /*
   * Represents an object with no predefined structure
   */
  BLIZZARD__DESCRIPTOR__BASIC_TYPES__ANY_OBJECT = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BLIZZARD__DESCRIPTOR__BASIC_TYPES)
} Blizzard__Descriptor__BasicTypes;

/* --- messages --- */

typedef enum {
  BLIZZARD__DESCRIPTOR__DESCRIPTOR__KIND__NOT_SET = 0,
  BLIZZARD__DESCRIPTOR__DESCRIPTOR__KIND_BASIC = 1,
  BLIZZARD__DESCRIPTOR__DESCRIPTOR__KIND_LIST = 2,
  BLIZZARD__DESCRIPTOR__DESCRIPTOR__KIND_OBJECT = 3,
  BLIZZARD__DESCRIPTOR__DESCRIPTOR__KIND_OPTIONAL = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BLIZZARD__DESCRIPTOR__DESCRIPTOR__KIND__CASE)
} Blizzard__Descriptor__Descriptor__KindCase;

struct  Blizzard__Descriptor__Descriptor
{
  ProtobufCMessage base;
  Blizzard__Descriptor__Descriptor__KindCase kind_case;
  union {
    Blizzard__Descriptor__List *list;
    Blizzard__Descriptor__Object *object;
    Blizzard__Descriptor__Optional *optional;
    Blizzard__Descriptor__BasicTypes basic;
  };
};
#define BLIZZARD__DESCRIPTOR__DESCRIPTOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__descriptor__descriptor__descriptor) \
, BLIZZARD__DESCRIPTOR__DESCRIPTOR__KIND__NOT_SET, {0} }


struct  Blizzard__Descriptor__List
{
  ProtobufCMessage base;
  Blizzard__Descriptor__Descriptor *items;
};
#define BLIZZARD__DESCRIPTOR__LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__descriptor__list__descriptor) \
, NULL }


struct  Blizzard__Descriptor__Object__PropertiesEntry
{
  ProtobufCMessage base;
  char *key;
  Blizzard__Descriptor__Descriptor *value;
};
#define BLIZZARD__DESCRIPTOR__OBJECT__PROPERTIES_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__descriptor__object__properties_entry__descriptor) \
, (char *)protobuf_c_empty_string, NULL }


struct  Blizzard__Descriptor__Object
{
  ProtobufCMessage base;
  size_t n_properties;
  Blizzard__Descriptor__Object__PropertiesEntry **properties;
};
#define BLIZZARD__DESCRIPTOR__OBJECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__descriptor__object__descriptor) \
, 0,NULL }


struct  Blizzard__Descriptor__Optional
{
  ProtobufCMessage base;
  Blizzard__Descriptor__Descriptor *item;
};
#define BLIZZARD__DESCRIPTOR__OPTIONAL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__descriptor__optional__descriptor) \
, NULL }


/* Blizzard__Descriptor__Descriptor methods */
void   blizzard__descriptor__descriptor__init
                     (Blizzard__Descriptor__Descriptor         *message);
size_t blizzard__descriptor__descriptor__get_packed_size
                     (const Blizzard__Descriptor__Descriptor   *message);
size_t blizzard__descriptor__descriptor__pack
                     (const Blizzard__Descriptor__Descriptor   *message,
                      uint8_t             *out);
size_t blizzard__descriptor__descriptor__pack_to_buffer
                     (const Blizzard__Descriptor__Descriptor   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Descriptor__Descriptor *
       blizzard__descriptor__descriptor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__descriptor__descriptor__free_unpacked
                     (Blizzard__Descriptor__Descriptor *message,
                      ProtobufCAllocator *allocator);
/* Blizzard__Descriptor__List methods */
void   blizzard__descriptor__list__init
                     (Blizzard__Descriptor__List         *message);
size_t blizzard__descriptor__list__get_packed_size
                     (const Blizzard__Descriptor__List   *message);
size_t blizzard__descriptor__list__pack
                     (const Blizzard__Descriptor__List   *message,
                      uint8_t             *out);
size_t blizzard__descriptor__list__pack_to_buffer
                     (const Blizzard__Descriptor__List   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Descriptor__List *
       blizzard__descriptor__list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__descriptor__list__free_unpacked
                     (Blizzard__Descriptor__List *message,
                      ProtobufCAllocator *allocator);
/* Blizzard__Descriptor__Object__PropertiesEntry methods */
void   blizzard__descriptor__object__properties_entry__init
                     (Blizzard__Descriptor__Object__PropertiesEntry         *message);
/* Blizzard__Descriptor__Object methods */
void   blizzard__descriptor__object__init
                     (Blizzard__Descriptor__Object         *message);
size_t blizzard__descriptor__object__get_packed_size
                     (const Blizzard__Descriptor__Object   *message);
size_t blizzard__descriptor__object__pack
                     (const Blizzard__Descriptor__Object   *message,
                      uint8_t             *out);
size_t blizzard__descriptor__object__pack_to_buffer
                     (const Blizzard__Descriptor__Object   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Descriptor__Object *
       blizzard__descriptor__object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__descriptor__object__free_unpacked
                     (Blizzard__Descriptor__Object *message,
                      ProtobufCAllocator *allocator);
/* Blizzard__Descriptor__Optional methods */
void   blizzard__descriptor__optional__init
                     (Blizzard__Descriptor__Optional         *message);
size_t blizzard__descriptor__optional__get_packed_size
                     (const Blizzard__Descriptor__Optional   *message);
size_t blizzard__descriptor__optional__pack
                     (const Blizzard__Descriptor__Optional   *message,
                      uint8_t             *out);
size_t blizzard__descriptor__optional__pack_to_buffer
                     (const Blizzard__Descriptor__Optional   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Descriptor__Optional *
       blizzard__descriptor__optional__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__descriptor__optional__free_unpacked
                     (Blizzard__Descriptor__Optional *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Blizzard__Descriptor__Descriptor_Closure)
                 (const Blizzard__Descriptor__Descriptor *message,
                  void *closure_data);
typedef void (*Blizzard__Descriptor__List_Closure)
                 (const Blizzard__Descriptor__List *message,
                  void *closure_data);
typedef void (*Blizzard__Descriptor__Object__PropertiesEntry_Closure)
                 (const Blizzard__Descriptor__Object__PropertiesEntry *message,
                  void *closure_data);
typedef void (*Blizzard__Descriptor__Object_Closure)
                 (const Blizzard__Descriptor__Object *message,
                  void *closure_data);
typedef void (*Blizzard__Descriptor__Optional_Closure)
                 (const Blizzard__Descriptor__Optional *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    blizzard__descriptor__basic_types__descriptor;
extern const ProtobufCMessageDescriptor blizzard__descriptor__descriptor__descriptor;
extern const ProtobufCMessageDescriptor blizzard__descriptor__list__descriptor;
extern const ProtobufCMessageDescriptor blizzard__descriptor__object__descriptor;
extern const ProtobufCMessageDescriptor blizzard__descriptor__object__properties_entry__descriptor;
extern const ProtobufCMessageDescriptor blizzard__descriptor__optional__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_descriptor_2eproto__INCLUDED */
