/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: descriptor.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "descriptor.pb-c.h"
void   blizzard__descriptor__descriptor__init
                     (Blizzard__Descriptor__Descriptor         *message)
{
  static const Blizzard__Descriptor__Descriptor init_value = BLIZZARD__DESCRIPTOR__DESCRIPTOR__INIT;
  *message = init_value;
}
size_t blizzard__descriptor__descriptor__get_packed_size
                     (const Blizzard__Descriptor__Descriptor *message)
{
  assert(message->base.descriptor == &blizzard__descriptor__descriptor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__descriptor__descriptor__pack
                     (const Blizzard__Descriptor__Descriptor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__descriptor__descriptor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__descriptor__descriptor__pack_to_buffer
                     (const Blizzard__Descriptor__Descriptor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__descriptor__descriptor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Descriptor__Descriptor *
       blizzard__descriptor__descriptor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Descriptor__Descriptor *)
     protobuf_c_message_unpack (&blizzard__descriptor__descriptor__descriptor,
                                allocator, len, data);
}
void   blizzard__descriptor__descriptor__free_unpacked
                     (Blizzard__Descriptor__Descriptor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__descriptor__descriptor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blizzard__descriptor__list__init
                     (Blizzard__Descriptor__List         *message)
{
  static const Blizzard__Descriptor__List init_value = BLIZZARD__DESCRIPTOR__LIST__INIT;
  *message = init_value;
}
size_t blizzard__descriptor__list__get_packed_size
                     (const Blizzard__Descriptor__List *message)
{
  assert(message->base.descriptor == &blizzard__descriptor__list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__descriptor__list__pack
                     (const Blizzard__Descriptor__List *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__descriptor__list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__descriptor__list__pack_to_buffer
                     (const Blizzard__Descriptor__List *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__descriptor__list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Descriptor__List *
       blizzard__descriptor__list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Descriptor__List *)
     protobuf_c_message_unpack (&blizzard__descriptor__list__descriptor,
                                allocator, len, data);
}
void   blizzard__descriptor__list__free_unpacked
                     (Blizzard__Descriptor__List *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__descriptor__list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blizzard__descriptor__object__properties_entry__init
                     (Blizzard__Descriptor__Object__PropertiesEntry         *message)
{
  static const Blizzard__Descriptor__Object__PropertiesEntry init_value = BLIZZARD__DESCRIPTOR__OBJECT__PROPERTIES_ENTRY__INIT;
  *message = init_value;
}
void   blizzard__descriptor__object__init
                     (Blizzard__Descriptor__Object         *message)
{
  static const Blizzard__Descriptor__Object init_value = BLIZZARD__DESCRIPTOR__OBJECT__INIT;
  *message = init_value;
}
size_t blizzard__descriptor__object__get_packed_size
                     (const Blizzard__Descriptor__Object *message)
{
  assert(message->base.descriptor == &blizzard__descriptor__object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__descriptor__object__pack
                     (const Blizzard__Descriptor__Object *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__descriptor__object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__descriptor__object__pack_to_buffer
                     (const Blizzard__Descriptor__Object *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__descriptor__object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Descriptor__Object *
       blizzard__descriptor__object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Descriptor__Object *)
     protobuf_c_message_unpack (&blizzard__descriptor__object__descriptor,
                                allocator, len, data);
}
void   blizzard__descriptor__object__free_unpacked
                     (Blizzard__Descriptor__Object *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__descriptor__object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blizzard__descriptor__optional__init
                     (Blizzard__Descriptor__Optional         *message)
{
  static const Blizzard__Descriptor__Optional init_value = BLIZZARD__DESCRIPTOR__OPTIONAL__INIT;
  *message = init_value;
}
size_t blizzard__descriptor__optional__get_packed_size
                     (const Blizzard__Descriptor__Optional *message)
{
  assert(message->base.descriptor == &blizzard__descriptor__optional__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__descriptor__optional__pack
                     (const Blizzard__Descriptor__Optional *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__descriptor__optional__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__descriptor__optional__pack_to_buffer
                     (const Blizzard__Descriptor__Optional *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__descriptor__optional__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Descriptor__Optional *
       blizzard__descriptor__optional__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Descriptor__Optional *)
     protobuf_c_message_unpack (&blizzard__descriptor__optional__descriptor,
                                allocator, len, data);
}
void   blizzard__descriptor__optional__free_unpacked
                     (Blizzard__Descriptor__Optional *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__descriptor__optional__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor blizzard__descriptor__descriptor__field_descriptors[4] =
{
  {
    "basic",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Blizzard__Descriptor__Descriptor, kind_case),
    offsetof(Blizzard__Descriptor__Descriptor, basic),
    &blizzard__descriptor__basic_types__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "list",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Descriptor__Descriptor, kind_case),
    offsetof(Blizzard__Descriptor__Descriptor, list),
    &blizzard__descriptor__list__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Descriptor__Descriptor, kind_case),
    offsetof(Blizzard__Descriptor__Descriptor, object),
    &blizzard__descriptor__object__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "optional",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Descriptor__Descriptor, kind_case),
    offsetof(Blizzard__Descriptor__Descriptor, optional),
    &blizzard__descriptor__optional__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__descriptor__descriptor__field_indices_by_name[] = {
  0,   /* field[0] = basic */
  1,   /* field[1] = list */
  2,   /* field[2] = object */
  3,   /* field[3] = optional */
};
static const ProtobufCIntRange blizzard__descriptor__descriptor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor blizzard__descriptor__descriptor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.descriptor.Descriptor",
  "Descriptor",
  "Blizzard__Descriptor__Descriptor",
  "blizzard.descriptor",
  sizeof(Blizzard__Descriptor__Descriptor),
  4,
  blizzard__descriptor__descriptor__field_descriptors,
  blizzard__descriptor__descriptor__field_indices_by_name,
  1,  blizzard__descriptor__descriptor__number_ranges,
  (ProtobufCMessageInit) blizzard__descriptor__descriptor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__descriptor__list__field_descriptors[1] =
{
  {
    "items",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Descriptor__List, items),
    &blizzard__descriptor__descriptor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__descriptor__list__field_indices_by_name[] = {
  0,   /* field[0] = items */
};
static const ProtobufCIntRange blizzard__descriptor__list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor blizzard__descriptor__list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.descriptor.List",
  "List",
  "Blizzard__Descriptor__List",
  "blizzard.descriptor",
  sizeof(Blizzard__Descriptor__List),
  1,
  blizzard__descriptor__list__field_descriptors,
  blizzard__descriptor__list__field_indices_by_name,
  1,  blizzard__descriptor__list__number_ranges,
  (ProtobufCMessageInit) blizzard__descriptor__list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__descriptor__object__properties_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Descriptor__Object__PropertiesEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Descriptor__Object__PropertiesEntry, value),
    &blizzard__descriptor__descriptor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__descriptor__object__properties_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange blizzard__descriptor__object__properties_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor blizzard__descriptor__object__properties_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.descriptor.Object.PropertiesEntry",
  "PropertiesEntry",
  "Blizzard__Descriptor__Object__PropertiesEntry",
  "blizzard.descriptor",
  sizeof(Blizzard__Descriptor__Object__PropertiesEntry),
  2,
  blizzard__descriptor__object__properties_entry__field_descriptors,
  blizzard__descriptor__object__properties_entry__field_indices_by_name,
  1,  blizzard__descriptor__object__properties_entry__number_ranges,
  (ProtobufCMessageInit) blizzard__descriptor__object__properties_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__descriptor__object__field_descriptors[1] =
{
  {
    "properties",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Descriptor__Object, n_properties),
    offsetof(Blizzard__Descriptor__Object, properties),
    &blizzard__descriptor__object__properties_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__descriptor__object__field_indices_by_name[] = {
  0,   /* field[0] = properties */
};
static const ProtobufCIntRange blizzard__descriptor__object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor blizzard__descriptor__object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.descriptor.Object",
  "Object",
  "Blizzard__Descriptor__Object",
  "blizzard.descriptor",
  sizeof(Blizzard__Descriptor__Object),
  1,
  blizzard__descriptor__object__field_descriptors,
  blizzard__descriptor__object__field_indices_by_name,
  1,  blizzard__descriptor__object__number_ranges,
  (ProtobufCMessageInit) blizzard__descriptor__object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__descriptor__optional__field_descriptors[1] =
{
  {
    "item",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Descriptor__Optional, item),
    &blizzard__descriptor__descriptor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__descriptor__optional__field_indices_by_name[] = {
  0,   /* field[0] = item */
};
static const ProtobufCIntRange blizzard__descriptor__optional__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor blizzard__descriptor__optional__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.descriptor.Optional",
  "Optional",
  "Blizzard__Descriptor__Optional",
  "blizzard.descriptor",
  sizeof(Blizzard__Descriptor__Optional),
  1,
  blizzard__descriptor__optional__field_descriptors,
  blizzard__descriptor__optional__field_indices_by_name,
  1,  blizzard__descriptor__optional__number_ranges,
  (ProtobufCMessageInit) blizzard__descriptor__optional__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue blizzard__descriptor__basic_types__enum_values_by_number[7] =
{
  { "BOOLEAN", "BLIZZARD__DESCRIPTOR__BASIC_TYPES__BOOLEAN", 0 },
  { "INTEGER", "BLIZZARD__DESCRIPTOR__BASIC_TYPES__INTEGER", 1 },
  { "DOUBLE", "BLIZZARD__DESCRIPTOR__BASIC_TYPES__DOUBLE", 2 },
  { "STRING", "BLIZZARD__DESCRIPTOR__BASIC_TYPES__STRING", 3 },
  { "BYTES", "BLIZZARD__DESCRIPTOR__BASIC_TYPES__BYTES", 4 },
  { "ANY", "BLIZZARD__DESCRIPTOR__BASIC_TYPES__ANY", 5 },
  { "ANY_OBJECT", "BLIZZARD__DESCRIPTOR__BASIC_TYPES__ANY_OBJECT", 6 },
};
static const ProtobufCIntRange blizzard__descriptor__basic_types__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex blizzard__descriptor__basic_types__enum_values_by_name[7] =
{
  { "ANY", 5 },
  { "ANY_OBJECT", 6 },
  { "BOOLEAN", 0 },
  { "BYTES", 4 },
  { "DOUBLE", 2 },
  { "INTEGER", 1 },
  { "STRING", 3 },
};
const ProtobufCEnumDescriptor blizzard__descriptor__basic_types__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "blizzard.descriptor.BasicTypes",
  "BasicTypes",
  "Blizzard__Descriptor__BasicTypes",
  "blizzard.descriptor",
  7,
  blizzard__descriptor__basic_types__enum_values_by_number,
  7,
  blizzard__descriptor__basic_types__enum_values_by_name,
  1,
  blizzard__descriptor__basic_types__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
