/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

#ifndef PROTOBUF_C_messages_2eproto__INCLUDED
#define PROTOBUF_C_messages_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "google/protobuf/any.pb-c.h"
#include "google/protobuf/empty.pb-c.h"

typedef struct Blizzard__Plugin__Messages__PluginToManagerMessage Blizzard__Plugin__Messages__PluginToManagerMessage;
typedef struct Blizzard__Plugin__Messages__ManagerToPluginMessage Blizzard__Plugin__Messages__ManagerToPluginMessage;
typedef struct Blizzard__Plugin__Messages__RegistrationRequest Blizzard__Plugin__Messages__RegistrationRequest;
typedef struct Blizzard__Plugin__Messages__RegistrationResponse Blizzard__Plugin__Messages__RegistrationResponse;
typedef struct Blizzard__Plugin__Messages__InvokeRequest Blizzard__Plugin__Messages__InvokeRequest;
typedef struct Blizzard__Plugin__Messages__InvokeResponse Blizzard__Plugin__Messages__InvokeResponse;
typedef struct Blizzard__Plugin__Messages__PropertyGetRequest Blizzard__Plugin__Messages__PropertyGetRequest;
typedef struct Blizzard__Plugin__Messages__PropertyGetResponse Blizzard__Plugin__Messages__PropertyGetResponse;
typedef struct Blizzard__Plugin__Messages__PropertySetRequest Blizzard__Plugin__Messages__PropertySetRequest;
typedef struct Blizzard__Plugin__Messages__PropertySetResponse Blizzard__Plugin__Messages__PropertySetResponse;
typedef struct Blizzard__Plugin__Messages__Event Blizzard__Plugin__Messages__Event;


/* --- enums --- */


/* --- messages --- */

typedef enum {
  BLIZZARD__PLUGIN__MESSAGES__PLUGIN_TO_MANAGER_MESSAGE__MESSAGE__NOT_SET = 0,
  BLIZZARD__PLUGIN__MESSAGES__PLUGIN_TO_MANAGER_MESSAGE__MESSAGE_REGISTRATION_REQUEST = 1,
  BLIZZARD__PLUGIN__MESSAGES__PLUGIN_TO_MANAGER_MESSAGE__MESSAGE_INVOKE_RESPONSE = 2,
  BLIZZARD__PLUGIN__MESSAGES__PLUGIN_TO_MANAGER_MESSAGE__MESSAGE_PROPERTY_GET_RESPONSE = 3,
  BLIZZARD__PLUGIN__MESSAGES__PLUGIN_TO_MANAGER_MESSAGE__MESSAGE_PROPERTY_SET_RESPONSE = 4,
  BLIZZARD__PLUGIN__MESSAGES__PLUGIN_TO_MANAGER_MESSAGE__MESSAGE_EVENT = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BLIZZARD__PLUGIN__MESSAGES__PLUGIN_TO_MANAGER_MESSAGE__MESSAGE__CASE)
} Blizzard__Plugin__Messages__PluginToManagerMessage__MessageCase;

struct  Blizzard__Plugin__Messages__PluginToManagerMessage
{
  ProtobufCMessage base;
  Blizzard__Plugin__Messages__PluginToManagerMessage__MessageCase message_case;
  union {
    Blizzard__Plugin__Messages__Event *event;
    Blizzard__Plugin__Messages__InvokeResponse *invoke_response;
    Blizzard__Plugin__Messages__PropertyGetResponse *property_get_response;
    Blizzard__Plugin__Messages__PropertySetResponse *property_set_response;
    Blizzard__Plugin__Messages__RegistrationRequest *registration_request;
  };
};
#define BLIZZARD__PLUGIN__MESSAGES__PLUGIN_TO_MANAGER_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__plugin__messages__plugin_to_manager_message__descriptor) \
, BLIZZARD__PLUGIN__MESSAGES__PLUGIN_TO_MANAGER_MESSAGE__MESSAGE__NOT_SET, {0} }


typedef enum {
  BLIZZARD__PLUGIN__MESSAGES__MANAGER_TO_PLUGIN_MESSAGE__MESSAGE__NOT_SET = 0,
  BLIZZARD__PLUGIN__MESSAGES__MANAGER_TO_PLUGIN_MESSAGE__MESSAGE_REGISTRATION_RESPONSE = 1,
  BLIZZARD__PLUGIN__MESSAGES__MANAGER_TO_PLUGIN_MESSAGE__MESSAGE_INVOKE_REQUEST = 2,
  BLIZZARD__PLUGIN__MESSAGES__MANAGER_TO_PLUGIN_MESSAGE__MESSAGE_PROPERTY_GET_REQUEST = 3,
  BLIZZARD__PLUGIN__MESSAGES__MANAGER_TO_PLUGIN_MESSAGE__MESSAGE_PROPERTY_SET_REQUEST = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BLIZZARD__PLUGIN__MESSAGES__MANAGER_TO_PLUGIN_MESSAGE__MESSAGE__CASE)
} Blizzard__Plugin__Messages__ManagerToPluginMessage__MessageCase;

struct  Blizzard__Plugin__Messages__ManagerToPluginMessage
{
  ProtobufCMessage base;
  Blizzard__Plugin__Messages__ManagerToPluginMessage__MessageCase message_case;
  union {
    Blizzard__Plugin__Messages__InvokeRequest *invoke_request;
    Blizzard__Plugin__Messages__PropertyGetRequest *property_get_request;
    Blizzard__Plugin__Messages__PropertySetRequest *property_set_request;
    Blizzard__Plugin__Messages__RegistrationResponse *registration_response;
  };
};
#define BLIZZARD__PLUGIN__MESSAGES__MANAGER_TO_PLUGIN_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__plugin__messages__manager_to_plugin_message__descriptor) \
, BLIZZARD__PLUGIN__MESSAGES__MANAGER_TO_PLUGIN_MESSAGE__MESSAGE__NOT_SET, {0} }


struct  Blizzard__Plugin__Messages__RegistrationRequest
{
  ProtobufCMessage base;
  Google__Protobuf__Any *description;
};
#define BLIZZARD__PLUGIN__MESSAGES__REGISTRATION_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__plugin__messages__registration_request__descriptor) \
, NULL }


struct  Blizzard__Plugin__Messages__RegistrationResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean status;
};
#define BLIZZARD__PLUGIN__MESSAGES__REGISTRATION_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__plugin__messages__registration_response__descriptor) \
, 0 }


struct  Blizzard__Plugin__Messages__InvokeRequest
{
  ProtobufCMessage base;
  uint64_t id;
  char *method;
  Google__Protobuf__Any *parameters;
};
#define BLIZZARD__PLUGIN__MESSAGES__INVOKE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__plugin__messages__invoke_request__descriptor) \
, 0, (char *)protobuf_c_empty_string, NULL }


typedef enum {
  BLIZZARD__PLUGIN__MESSAGES__INVOKE_RESPONSE__STATUS__NOT_SET = 0,
  BLIZZARD__PLUGIN__MESSAGES__INVOKE_RESPONSE__STATUS_SUCCESS = 2,
  BLIZZARD__PLUGIN__MESSAGES__INVOKE_RESPONSE__STATUS_ERROR = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BLIZZARD__PLUGIN__MESSAGES__INVOKE_RESPONSE__STATUS__CASE)
} Blizzard__Plugin__Messages__InvokeResponse__StatusCase;

struct  Blizzard__Plugin__Messages__InvokeResponse
{
  ProtobufCMessage base;
  uint64_t id;
  Blizzard__Plugin__Messages__InvokeResponse__StatusCase status_case;
  union {
    char *error;
    Google__Protobuf__Any *success;
  };
};
#define BLIZZARD__PLUGIN__MESSAGES__INVOKE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__plugin__messages__invoke_response__descriptor) \
, 0, BLIZZARD__PLUGIN__MESSAGES__INVOKE_RESPONSE__STATUS__NOT_SET, {0} }


struct  Blizzard__Plugin__Messages__PropertyGetRequest
{
  ProtobufCMessage base;
  uint64_t id;
  char *property;
};
#define BLIZZARD__PLUGIN__MESSAGES__PROPERTY_GET_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__plugin__messages__property_get_request__descriptor) \
, 0, (char *)protobuf_c_empty_string }


typedef enum {
  BLIZZARD__PLUGIN__MESSAGES__PROPERTY_GET_RESPONSE__STATUS__NOT_SET = 0,
  BLIZZARD__PLUGIN__MESSAGES__PROPERTY_GET_RESPONSE__STATUS_SUCCESS = 2,
  BLIZZARD__PLUGIN__MESSAGES__PROPERTY_GET_RESPONSE__STATUS_ERROR = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BLIZZARD__PLUGIN__MESSAGES__PROPERTY_GET_RESPONSE__STATUS__CASE)
} Blizzard__Plugin__Messages__PropertyGetResponse__StatusCase;

struct  Blizzard__Plugin__Messages__PropertyGetResponse
{
  ProtobufCMessage base;
  uint64_t id;
  Blizzard__Plugin__Messages__PropertyGetResponse__StatusCase status_case;
  union {
    char *error;
    Google__Protobuf__Any *success;
  };
};
#define BLIZZARD__PLUGIN__MESSAGES__PROPERTY_GET_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__plugin__messages__property_get_response__descriptor) \
, 0, BLIZZARD__PLUGIN__MESSAGES__PROPERTY_GET_RESPONSE__STATUS__NOT_SET, {0} }


struct  Blizzard__Plugin__Messages__PropertySetRequest
{
  ProtobufCMessage base;
  uint64_t id;
  char *property;
  Google__Protobuf__Any *value;
};
#define BLIZZARD__PLUGIN__MESSAGES__PROPERTY_SET_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__plugin__messages__property_set_request__descriptor) \
, 0, (char *)protobuf_c_empty_string, NULL }


typedef enum {
  BLIZZARD__PLUGIN__MESSAGES__PROPERTY_SET_RESPONSE__STATUS__NOT_SET = 0,
  BLIZZARD__PLUGIN__MESSAGES__PROPERTY_SET_RESPONSE__STATUS_SUCCESS = 2,
  BLIZZARD__PLUGIN__MESSAGES__PROPERTY_SET_RESPONSE__STATUS_ERROR = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BLIZZARD__PLUGIN__MESSAGES__PROPERTY_SET_RESPONSE__STATUS__CASE)
} Blizzard__Plugin__Messages__PropertySetResponse__StatusCase;

struct  Blizzard__Plugin__Messages__PropertySetResponse
{
  ProtobufCMessage base;
  uint64_t id;
  Blizzard__Plugin__Messages__PropertySetResponse__StatusCase status_case;
  union {
    char *error;
    Google__Protobuf__Empty *success;
  };
};
#define BLIZZARD__PLUGIN__MESSAGES__PROPERTY_SET_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__plugin__messages__property_set_response__descriptor) \
, 0, BLIZZARD__PLUGIN__MESSAGES__PROPERTY_SET_RESPONSE__STATUS__NOT_SET, {0} }


struct  Blizzard__Plugin__Messages__Event
{
  ProtobufCMessage base;
  char *name;
  Google__Protobuf__Any *value;
};
#define BLIZZARD__PLUGIN__MESSAGES__EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__plugin__messages__event__descriptor) \
, (char *)protobuf_c_empty_string, NULL }


/* Blizzard__Plugin__Messages__PluginToManagerMessage methods */
void   blizzard__plugin__messages__plugin_to_manager_message__init
                     (Blizzard__Plugin__Messages__PluginToManagerMessage         *message);
size_t blizzard__plugin__messages__plugin_to_manager_message__get_packed_size
                     (const Blizzard__Plugin__Messages__PluginToManagerMessage   *message);
size_t blizzard__plugin__messages__plugin_to_manager_message__pack
                     (const Blizzard__Plugin__Messages__PluginToManagerMessage   *message,
                      uint8_t             *out);
size_t blizzard__plugin__messages__plugin_to_manager_message__pack_to_buffer
                     (const Blizzard__Plugin__Messages__PluginToManagerMessage   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Plugin__Messages__PluginToManagerMessage *
       blizzard__plugin__messages__plugin_to_manager_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__plugin__messages__plugin_to_manager_message__free_unpacked
                     (Blizzard__Plugin__Messages__PluginToManagerMessage *message,
                      ProtobufCAllocator *allocator);
/* Blizzard__Plugin__Messages__ManagerToPluginMessage methods */
void   blizzard__plugin__messages__manager_to_plugin_message__init
                     (Blizzard__Plugin__Messages__ManagerToPluginMessage         *message);
size_t blizzard__plugin__messages__manager_to_plugin_message__get_packed_size
                     (const Blizzard__Plugin__Messages__ManagerToPluginMessage   *message);
size_t blizzard__plugin__messages__manager_to_plugin_message__pack
                     (const Blizzard__Plugin__Messages__ManagerToPluginMessage   *message,
                      uint8_t             *out);
size_t blizzard__plugin__messages__manager_to_plugin_message__pack_to_buffer
                     (const Blizzard__Plugin__Messages__ManagerToPluginMessage   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Plugin__Messages__ManagerToPluginMessage *
       blizzard__plugin__messages__manager_to_plugin_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__plugin__messages__manager_to_plugin_message__free_unpacked
                     (Blizzard__Plugin__Messages__ManagerToPluginMessage *message,
                      ProtobufCAllocator *allocator);
/* Blizzard__Plugin__Messages__RegistrationRequest methods */
void   blizzard__plugin__messages__registration_request__init
                     (Blizzard__Plugin__Messages__RegistrationRequest         *message);
size_t blizzard__plugin__messages__registration_request__get_packed_size
                     (const Blizzard__Plugin__Messages__RegistrationRequest   *message);
size_t blizzard__plugin__messages__registration_request__pack
                     (const Blizzard__Plugin__Messages__RegistrationRequest   *message,
                      uint8_t             *out);
size_t blizzard__plugin__messages__registration_request__pack_to_buffer
                     (const Blizzard__Plugin__Messages__RegistrationRequest   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Plugin__Messages__RegistrationRequest *
       blizzard__plugin__messages__registration_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__plugin__messages__registration_request__free_unpacked
                     (Blizzard__Plugin__Messages__RegistrationRequest *message,
                      ProtobufCAllocator *allocator);
/* Blizzard__Plugin__Messages__RegistrationResponse methods */
void   blizzard__plugin__messages__registration_response__init
                     (Blizzard__Plugin__Messages__RegistrationResponse         *message);
size_t blizzard__plugin__messages__registration_response__get_packed_size
                     (const Blizzard__Plugin__Messages__RegistrationResponse   *message);
size_t blizzard__plugin__messages__registration_response__pack
                     (const Blizzard__Plugin__Messages__RegistrationResponse   *message,
                      uint8_t             *out);
size_t blizzard__plugin__messages__registration_response__pack_to_buffer
                     (const Blizzard__Plugin__Messages__RegistrationResponse   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Plugin__Messages__RegistrationResponse *
       blizzard__plugin__messages__registration_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__plugin__messages__registration_response__free_unpacked
                     (Blizzard__Plugin__Messages__RegistrationResponse *message,
                      ProtobufCAllocator *allocator);
/* Blizzard__Plugin__Messages__InvokeRequest methods */
void   blizzard__plugin__messages__invoke_request__init
                     (Blizzard__Plugin__Messages__InvokeRequest         *message);
size_t blizzard__plugin__messages__invoke_request__get_packed_size
                     (const Blizzard__Plugin__Messages__InvokeRequest   *message);
size_t blizzard__plugin__messages__invoke_request__pack
                     (const Blizzard__Plugin__Messages__InvokeRequest   *message,
                      uint8_t             *out);
size_t blizzard__plugin__messages__invoke_request__pack_to_buffer
                     (const Blizzard__Plugin__Messages__InvokeRequest   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Plugin__Messages__InvokeRequest *
       blizzard__plugin__messages__invoke_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__plugin__messages__invoke_request__free_unpacked
                     (Blizzard__Plugin__Messages__InvokeRequest *message,
                      ProtobufCAllocator *allocator);
/* Blizzard__Plugin__Messages__InvokeResponse methods */
void   blizzard__plugin__messages__invoke_response__init
                     (Blizzard__Plugin__Messages__InvokeResponse         *message);
size_t blizzard__plugin__messages__invoke_response__get_packed_size
                     (const Blizzard__Plugin__Messages__InvokeResponse   *message);
size_t blizzard__plugin__messages__invoke_response__pack
                     (const Blizzard__Plugin__Messages__InvokeResponse   *message,
                      uint8_t             *out);
size_t blizzard__plugin__messages__invoke_response__pack_to_buffer
                     (const Blizzard__Plugin__Messages__InvokeResponse   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Plugin__Messages__InvokeResponse *
       blizzard__plugin__messages__invoke_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__plugin__messages__invoke_response__free_unpacked
                     (Blizzard__Plugin__Messages__InvokeResponse *message,
                      ProtobufCAllocator *allocator);
/* Blizzard__Plugin__Messages__PropertyGetRequest methods */
void   blizzard__plugin__messages__property_get_request__init
                     (Blizzard__Plugin__Messages__PropertyGetRequest         *message);
size_t blizzard__plugin__messages__property_get_request__get_packed_size
                     (const Blizzard__Plugin__Messages__PropertyGetRequest   *message);
size_t blizzard__plugin__messages__property_get_request__pack
                     (const Blizzard__Plugin__Messages__PropertyGetRequest   *message,
                      uint8_t             *out);
size_t blizzard__plugin__messages__property_get_request__pack_to_buffer
                     (const Blizzard__Plugin__Messages__PropertyGetRequest   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Plugin__Messages__PropertyGetRequest *
       blizzard__plugin__messages__property_get_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__plugin__messages__property_get_request__free_unpacked
                     (Blizzard__Plugin__Messages__PropertyGetRequest *message,
                      ProtobufCAllocator *allocator);
/* Blizzard__Plugin__Messages__PropertyGetResponse methods */
void   blizzard__plugin__messages__property_get_response__init
                     (Blizzard__Plugin__Messages__PropertyGetResponse         *message);
size_t blizzard__plugin__messages__property_get_response__get_packed_size
                     (const Blizzard__Plugin__Messages__PropertyGetResponse   *message);
size_t blizzard__plugin__messages__property_get_response__pack
                     (const Blizzard__Plugin__Messages__PropertyGetResponse   *message,
                      uint8_t             *out);
size_t blizzard__plugin__messages__property_get_response__pack_to_buffer
                     (const Blizzard__Plugin__Messages__PropertyGetResponse   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Plugin__Messages__PropertyGetResponse *
       blizzard__plugin__messages__property_get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__plugin__messages__property_get_response__free_unpacked
                     (Blizzard__Plugin__Messages__PropertyGetResponse *message,
                      ProtobufCAllocator *allocator);
/* Blizzard__Plugin__Messages__PropertySetRequest methods */
void   blizzard__plugin__messages__property_set_request__init
                     (Blizzard__Plugin__Messages__PropertySetRequest         *message);
size_t blizzard__plugin__messages__property_set_request__get_packed_size
                     (const Blizzard__Plugin__Messages__PropertySetRequest   *message);
size_t blizzard__plugin__messages__property_set_request__pack
                     (const Blizzard__Plugin__Messages__PropertySetRequest   *message,
                      uint8_t             *out);
size_t blizzard__plugin__messages__property_set_request__pack_to_buffer
                     (const Blizzard__Plugin__Messages__PropertySetRequest   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Plugin__Messages__PropertySetRequest *
       blizzard__plugin__messages__property_set_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__plugin__messages__property_set_request__free_unpacked
                     (Blizzard__Plugin__Messages__PropertySetRequest *message,
                      ProtobufCAllocator *allocator);
/* Blizzard__Plugin__Messages__PropertySetResponse methods */
void   blizzard__plugin__messages__property_set_response__init
                     (Blizzard__Plugin__Messages__PropertySetResponse         *message);
size_t blizzard__plugin__messages__property_set_response__get_packed_size
                     (const Blizzard__Plugin__Messages__PropertySetResponse   *message);
size_t blizzard__plugin__messages__property_set_response__pack
                     (const Blizzard__Plugin__Messages__PropertySetResponse   *message,
                      uint8_t             *out);
size_t blizzard__plugin__messages__property_set_response__pack_to_buffer
                     (const Blizzard__Plugin__Messages__PropertySetResponse   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Plugin__Messages__PropertySetResponse *
       blizzard__plugin__messages__property_set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__plugin__messages__property_set_response__free_unpacked
                     (Blizzard__Plugin__Messages__PropertySetResponse *message,
                      ProtobufCAllocator *allocator);
/* Blizzard__Plugin__Messages__Event methods */
void   blizzard__plugin__messages__event__init
                     (Blizzard__Plugin__Messages__Event         *message);
size_t blizzard__plugin__messages__event__get_packed_size
                     (const Blizzard__Plugin__Messages__Event   *message);
size_t blizzard__plugin__messages__event__pack
                     (const Blizzard__Plugin__Messages__Event   *message,
                      uint8_t             *out);
size_t blizzard__plugin__messages__event__pack_to_buffer
                     (const Blizzard__Plugin__Messages__Event   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Plugin__Messages__Event *
       blizzard__plugin__messages__event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__plugin__messages__event__free_unpacked
                     (Blizzard__Plugin__Messages__Event *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Blizzard__Plugin__Messages__PluginToManagerMessage_Closure)
                 (const Blizzard__Plugin__Messages__PluginToManagerMessage *message,
                  void *closure_data);
typedef void (*Blizzard__Plugin__Messages__ManagerToPluginMessage_Closure)
                 (const Blizzard__Plugin__Messages__ManagerToPluginMessage *message,
                  void *closure_data);
typedef void (*Blizzard__Plugin__Messages__RegistrationRequest_Closure)
                 (const Blizzard__Plugin__Messages__RegistrationRequest *message,
                  void *closure_data);
typedef void (*Blizzard__Plugin__Messages__RegistrationResponse_Closure)
                 (const Blizzard__Plugin__Messages__RegistrationResponse *message,
                  void *closure_data);
typedef void (*Blizzard__Plugin__Messages__InvokeRequest_Closure)
                 (const Blizzard__Plugin__Messages__InvokeRequest *message,
                  void *closure_data);
typedef void (*Blizzard__Plugin__Messages__InvokeResponse_Closure)
                 (const Blizzard__Plugin__Messages__InvokeResponse *message,
                  void *closure_data);
typedef void (*Blizzard__Plugin__Messages__PropertyGetRequest_Closure)
                 (const Blizzard__Plugin__Messages__PropertyGetRequest *message,
                  void *closure_data);
typedef void (*Blizzard__Plugin__Messages__PropertyGetResponse_Closure)
                 (const Blizzard__Plugin__Messages__PropertyGetResponse *message,
                  void *closure_data);
typedef void (*Blizzard__Plugin__Messages__PropertySetRequest_Closure)
                 (const Blizzard__Plugin__Messages__PropertySetRequest *message,
                  void *closure_data);
typedef void (*Blizzard__Plugin__Messages__PropertySetResponse_Closure)
                 (const Blizzard__Plugin__Messages__PropertySetResponse *message,
                  void *closure_data);
typedef void (*Blizzard__Plugin__Messages__Event_Closure)
                 (const Blizzard__Plugin__Messages__Event *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor blizzard__plugin__messages__plugin_to_manager_message__descriptor;
extern const ProtobufCMessageDescriptor blizzard__plugin__messages__manager_to_plugin_message__descriptor;
extern const ProtobufCMessageDescriptor blizzard__plugin__messages__registration_request__descriptor;
extern const ProtobufCMessageDescriptor blizzard__plugin__messages__registration_response__descriptor;
extern const ProtobufCMessageDescriptor blizzard__plugin__messages__invoke_request__descriptor;
extern const ProtobufCMessageDescriptor blizzard__plugin__messages__invoke_response__descriptor;
extern const ProtobufCMessageDescriptor blizzard__plugin__messages__property_get_request__descriptor;
extern const ProtobufCMessageDescriptor blizzard__plugin__messages__property_get_response__descriptor;
extern const ProtobufCMessageDescriptor blizzard__plugin__messages__property_set_request__descriptor;
extern const ProtobufCMessageDescriptor blizzard__plugin__messages__property_set_response__descriptor;
extern const ProtobufCMessageDescriptor blizzard__plugin__messages__event__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messages_2eproto__INCLUDED */
