/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages.pb-c.h"
void   blizzard__plugin__messages__plugin_to_manager_message__init
                     (Blizzard__Plugin__Messages__PluginToManagerMessage         *message)
{
  static const Blizzard__Plugin__Messages__PluginToManagerMessage init_value = BLIZZARD__PLUGIN__MESSAGES__PLUGIN_TO_MANAGER_MESSAGE__INIT;
  *message = init_value;
}
size_t blizzard__plugin__messages__plugin_to_manager_message__get_packed_size
                     (const Blizzard__Plugin__Messages__PluginToManagerMessage *message)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__plugin_to_manager_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__plugin__messages__plugin_to_manager_message__pack
                     (const Blizzard__Plugin__Messages__PluginToManagerMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__plugin_to_manager_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__plugin__messages__plugin_to_manager_message__pack_to_buffer
                     (const Blizzard__Plugin__Messages__PluginToManagerMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__plugin_to_manager_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Plugin__Messages__PluginToManagerMessage *
       blizzard__plugin__messages__plugin_to_manager_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Plugin__Messages__PluginToManagerMessage *)
     protobuf_c_message_unpack (&blizzard__plugin__messages__plugin_to_manager_message__descriptor,
                                allocator, len, data);
}
void   blizzard__plugin__messages__plugin_to_manager_message__free_unpacked
                     (Blizzard__Plugin__Messages__PluginToManagerMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__plugin__messages__plugin_to_manager_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blizzard__plugin__messages__manager_to_plugin_message__init
                     (Blizzard__Plugin__Messages__ManagerToPluginMessage         *message)
{
  static const Blizzard__Plugin__Messages__ManagerToPluginMessage init_value = BLIZZARD__PLUGIN__MESSAGES__MANAGER_TO_PLUGIN_MESSAGE__INIT;
  *message = init_value;
}
size_t blizzard__plugin__messages__manager_to_plugin_message__get_packed_size
                     (const Blizzard__Plugin__Messages__ManagerToPluginMessage *message)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__manager_to_plugin_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__plugin__messages__manager_to_plugin_message__pack
                     (const Blizzard__Plugin__Messages__ManagerToPluginMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__manager_to_plugin_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__plugin__messages__manager_to_plugin_message__pack_to_buffer
                     (const Blizzard__Plugin__Messages__ManagerToPluginMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__manager_to_plugin_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Plugin__Messages__ManagerToPluginMessage *
       blizzard__plugin__messages__manager_to_plugin_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Plugin__Messages__ManagerToPluginMessage *)
     protobuf_c_message_unpack (&blizzard__plugin__messages__manager_to_plugin_message__descriptor,
                                allocator, len, data);
}
void   blizzard__plugin__messages__manager_to_plugin_message__free_unpacked
                     (Blizzard__Plugin__Messages__ManagerToPluginMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__plugin__messages__manager_to_plugin_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blizzard__plugin__messages__registration_request__init
                     (Blizzard__Plugin__Messages__RegistrationRequest         *message)
{
  static const Blizzard__Plugin__Messages__RegistrationRequest init_value = BLIZZARD__PLUGIN__MESSAGES__REGISTRATION_REQUEST__INIT;
  *message = init_value;
}
size_t blizzard__plugin__messages__registration_request__get_packed_size
                     (const Blizzard__Plugin__Messages__RegistrationRequest *message)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__registration_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__plugin__messages__registration_request__pack
                     (const Blizzard__Plugin__Messages__RegistrationRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__registration_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__plugin__messages__registration_request__pack_to_buffer
                     (const Blizzard__Plugin__Messages__RegistrationRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__registration_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Plugin__Messages__RegistrationRequest *
       blizzard__plugin__messages__registration_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Plugin__Messages__RegistrationRequest *)
     protobuf_c_message_unpack (&blizzard__plugin__messages__registration_request__descriptor,
                                allocator, len, data);
}
void   blizzard__plugin__messages__registration_request__free_unpacked
                     (Blizzard__Plugin__Messages__RegistrationRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__plugin__messages__registration_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blizzard__plugin__messages__registration_response__init
                     (Blizzard__Plugin__Messages__RegistrationResponse         *message)
{
  static const Blizzard__Plugin__Messages__RegistrationResponse init_value = BLIZZARD__PLUGIN__MESSAGES__REGISTRATION_RESPONSE__INIT;
  *message = init_value;
}
size_t blizzard__plugin__messages__registration_response__get_packed_size
                     (const Blizzard__Plugin__Messages__RegistrationResponse *message)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__registration_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__plugin__messages__registration_response__pack
                     (const Blizzard__Plugin__Messages__RegistrationResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__registration_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__plugin__messages__registration_response__pack_to_buffer
                     (const Blizzard__Plugin__Messages__RegistrationResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__registration_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Plugin__Messages__RegistrationResponse *
       blizzard__plugin__messages__registration_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Plugin__Messages__RegistrationResponse *)
     protobuf_c_message_unpack (&blizzard__plugin__messages__registration_response__descriptor,
                                allocator, len, data);
}
void   blizzard__plugin__messages__registration_response__free_unpacked
                     (Blizzard__Plugin__Messages__RegistrationResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__plugin__messages__registration_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blizzard__plugin__messages__invoke_request__init
                     (Blizzard__Plugin__Messages__InvokeRequest         *message)
{
  static const Blizzard__Plugin__Messages__InvokeRequest init_value = BLIZZARD__PLUGIN__MESSAGES__INVOKE_REQUEST__INIT;
  *message = init_value;
}
size_t blizzard__plugin__messages__invoke_request__get_packed_size
                     (const Blizzard__Plugin__Messages__InvokeRequest *message)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__invoke_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__plugin__messages__invoke_request__pack
                     (const Blizzard__Plugin__Messages__InvokeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__invoke_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__plugin__messages__invoke_request__pack_to_buffer
                     (const Blizzard__Plugin__Messages__InvokeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__invoke_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Plugin__Messages__InvokeRequest *
       blizzard__plugin__messages__invoke_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Plugin__Messages__InvokeRequest *)
     protobuf_c_message_unpack (&blizzard__plugin__messages__invoke_request__descriptor,
                                allocator, len, data);
}
void   blizzard__plugin__messages__invoke_request__free_unpacked
                     (Blizzard__Plugin__Messages__InvokeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__plugin__messages__invoke_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blizzard__plugin__messages__invoke_response__init
                     (Blizzard__Plugin__Messages__InvokeResponse         *message)
{
  static const Blizzard__Plugin__Messages__InvokeResponse init_value = BLIZZARD__PLUGIN__MESSAGES__INVOKE_RESPONSE__INIT;
  *message = init_value;
}
size_t blizzard__plugin__messages__invoke_response__get_packed_size
                     (const Blizzard__Plugin__Messages__InvokeResponse *message)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__invoke_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__plugin__messages__invoke_response__pack
                     (const Blizzard__Plugin__Messages__InvokeResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__invoke_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__plugin__messages__invoke_response__pack_to_buffer
                     (const Blizzard__Plugin__Messages__InvokeResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__invoke_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Plugin__Messages__InvokeResponse *
       blizzard__plugin__messages__invoke_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Plugin__Messages__InvokeResponse *)
     protobuf_c_message_unpack (&blizzard__plugin__messages__invoke_response__descriptor,
                                allocator, len, data);
}
void   blizzard__plugin__messages__invoke_response__free_unpacked
                     (Blizzard__Plugin__Messages__InvokeResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__plugin__messages__invoke_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blizzard__plugin__messages__property_get_request__init
                     (Blizzard__Plugin__Messages__PropertyGetRequest         *message)
{
  static const Blizzard__Plugin__Messages__PropertyGetRequest init_value = BLIZZARD__PLUGIN__MESSAGES__PROPERTY_GET_REQUEST__INIT;
  *message = init_value;
}
size_t blizzard__plugin__messages__property_get_request__get_packed_size
                     (const Blizzard__Plugin__Messages__PropertyGetRequest *message)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__property_get_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__plugin__messages__property_get_request__pack
                     (const Blizzard__Plugin__Messages__PropertyGetRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__property_get_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__plugin__messages__property_get_request__pack_to_buffer
                     (const Blizzard__Plugin__Messages__PropertyGetRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__property_get_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Plugin__Messages__PropertyGetRequest *
       blizzard__plugin__messages__property_get_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Plugin__Messages__PropertyGetRequest *)
     protobuf_c_message_unpack (&blizzard__plugin__messages__property_get_request__descriptor,
                                allocator, len, data);
}
void   blizzard__plugin__messages__property_get_request__free_unpacked
                     (Blizzard__Plugin__Messages__PropertyGetRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__plugin__messages__property_get_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blizzard__plugin__messages__property_get_response__init
                     (Blizzard__Plugin__Messages__PropertyGetResponse         *message)
{
  static const Blizzard__Plugin__Messages__PropertyGetResponse init_value = BLIZZARD__PLUGIN__MESSAGES__PROPERTY_GET_RESPONSE__INIT;
  *message = init_value;
}
size_t blizzard__plugin__messages__property_get_response__get_packed_size
                     (const Blizzard__Plugin__Messages__PropertyGetResponse *message)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__property_get_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__plugin__messages__property_get_response__pack
                     (const Blizzard__Plugin__Messages__PropertyGetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__property_get_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__plugin__messages__property_get_response__pack_to_buffer
                     (const Blizzard__Plugin__Messages__PropertyGetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__property_get_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Plugin__Messages__PropertyGetResponse *
       blizzard__plugin__messages__property_get_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Plugin__Messages__PropertyGetResponse *)
     protobuf_c_message_unpack (&blizzard__plugin__messages__property_get_response__descriptor,
                                allocator, len, data);
}
void   blizzard__plugin__messages__property_get_response__free_unpacked
                     (Blizzard__Plugin__Messages__PropertyGetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__plugin__messages__property_get_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blizzard__plugin__messages__property_set_request__init
                     (Blizzard__Plugin__Messages__PropertySetRequest         *message)
{
  static const Blizzard__Plugin__Messages__PropertySetRequest init_value = BLIZZARD__PLUGIN__MESSAGES__PROPERTY_SET_REQUEST__INIT;
  *message = init_value;
}
size_t blizzard__plugin__messages__property_set_request__get_packed_size
                     (const Blizzard__Plugin__Messages__PropertySetRequest *message)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__property_set_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__plugin__messages__property_set_request__pack
                     (const Blizzard__Plugin__Messages__PropertySetRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__property_set_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__plugin__messages__property_set_request__pack_to_buffer
                     (const Blizzard__Plugin__Messages__PropertySetRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__property_set_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Plugin__Messages__PropertySetRequest *
       blizzard__plugin__messages__property_set_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Plugin__Messages__PropertySetRequest *)
     protobuf_c_message_unpack (&blizzard__plugin__messages__property_set_request__descriptor,
                                allocator, len, data);
}
void   blizzard__plugin__messages__property_set_request__free_unpacked
                     (Blizzard__Plugin__Messages__PropertySetRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__plugin__messages__property_set_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blizzard__plugin__messages__property_set_response__init
                     (Blizzard__Plugin__Messages__PropertySetResponse         *message)
{
  static const Blizzard__Plugin__Messages__PropertySetResponse init_value = BLIZZARD__PLUGIN__MESSAGES__PROPERTY_SET_RESPONSE__INIT;
  *message = init_value;
}
size_t blizzard__plugin__messages__property_set_response__get_packed_size
                     (const Blizzard__Plugin__Messages__PropertySetResponse *message)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__property_set_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__plugin__messages__property_set_response__pack
                     (const Blizzard__Plugin__Messages__PropertySetResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__property_set_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__plugin__messages__property_set_response__pack_to_buffer
                     (const Blizzard__Plugin__Messages__PropertySetResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__property_set_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Plugin__Messages__PropertySetResponse *
       blizzard__plugin__messages__property_set_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Plugin__Messages__PropertySetResponse *)
     protobuf_c_message_unpack (&blizzard__plugin__messages__property_set_response__descriptor,
                                allocator, len, data);
}
void   blizzard__plugin__messages__property_set_response__free_unpacked
                     (Blizzard__Plugin__Messages__PropertySetResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__plugin__messages__property_set_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blizzard__plugin__messages__event__init
                     (Blizzard__Plugin__Messages__Event         *message)
{
  static const Blizzard__Plugin__Messages__Event init_value = BLIZZARD__PLUGIN__MESSAGES__EVENT__INIT;
  *message = init_value;
}
size_t blizzard__plugin__messages__event__get_packed_size
                     (const Blizzard__Plugin__Messages__Event *message)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__plugin__messages__event__pack
                     (const Blizzard__Plugin__Messages__Event *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__plugin__messages__event__pack_to_buffer
                     (const Blizzard__Plugin__Messages__Event *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__plugin__messages__event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Plugin__Messages__Event *
       blizzard__plugin__messages__event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Plugin__Messages__Event *)
     protobuf_c_message_unpack (&blizzard__plugin__messages__event__descriptor,
                                allocator, len, data);
}
void   blizzard__plugin__messages__event__free_unpacked
                     (Blizzard__Plugin__Messages__Event *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__plugin__messages__event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor blizzard__plugin__messages__plugin_to_manager_message__field_descriptors[5] =
{
  {
    "registration_request",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Plugin__Messages__PluginToManagerMessage, message_case),
    offsetof(Blizzard__Plugin__Messages__PluginToManagerMessage, registration_request),
    &blizzard__plugin__messages__registration_request__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "invoke_response",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Plugin__Messages__PluginToManagerMessage, message_case),
    offsetof(Blizzard__Plugin__Messages__PluginToManagerMessage, invoke_response),
    &blizzard__plugin__messages__invoke_response__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "property_get_response",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Plugin__Messages__PluginToManagerMessage, message_case),
    offsetof(Blizzard__Plugin__Messages__PluginToManagerMessage, property_get_response),
    &blizzard__plugin__messages__property_get_response__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "property_set_response",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Plugin__Messages__PluginToManagerMessage, message_case),
    offsetof(Blizzard__Plugin__Messages__PluginToManagerMessage, property_set_response),
    &blizzard__plugin__messages__property_set_response__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "event",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Plugin__Messages__PluginToManagerMessage, message_case),
    offsetof(Blizzard__Plugin__Messages__PluginToManagerMessage, event),
    &blizzard__plugin__messages__event__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__plugin__messages__plugin_to_manager_message__field_indices_by_name[] = {
  4,   /* field[4] = event */
  1,   /* field[1] = invoke_response */
  2,   /* field[2] = property_get_response */
  3,   /* field[3] = property_set_response */
  0,   /* field[0] = registration_request */
};
static const ProtobufCIntRange blizzard__plugin__messages__plugin_to_manager_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor blizzard__plugin__messages__plugin_to_manager_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.plugin.messages.PluginToManagerMessage",
  "PluginToManagerMessage",
  "Blizzard__Plugin__Messages__PluginToManagerMessage",
  "blizzard.plugin.messages",
  sizeof(Blizzard__Plugin__Messages__PluginToManagerMessage),
  5,
  blizzard__plugin__messages__plugin_to_manager_message__field_descriptors,
  blizzard__plugin__messages__plugin_to_manager_message__field_indices_by_name,
  1,  blizzard__plugin__messages__plugin_to_manager_message__number_ranges,
  (ProtobufCMessageInit) blizzard__plugin__messages__plugin_to_manager_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__plugin__messages__manager_to_plugin_message__field_descriptors[4] =
{
  {
    "registration_response",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Plugin__Messages__ManagerToPluginMessage, message_case),
    offsetof(Blizzard__Plugin__Messages__ManagerToPluginMessage, registration_response),
    &blizzard__plugin__messages__registration_response__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "invoke_request",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Plugin__Messages__ManagerToPluginMessage, message_case),
    offsetof(Blizzard__Plugin__Messages__ManagerToPluginMessage, invoke_request),
    &blizzard__plugin__messages__invoke_request__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "property_get_request",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Plugin__Messages__ManagerToPluginMessage, message_case),
    offsetof(Blizzard__Plugin__Messages__ManagerToPluginMessage, property_get_request),
    &blizzard__plugin__messages__property_get_request__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "property_set_request",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Plugin__Messages__ManagerToPluginMessage, message_case),
    offsetof(Blizzard__Plugin__Messages__ManagerToPluginMessage, property_set_request),
    &blizzard__plugin__messages__property_set_request__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__plugin__messages__manager_to_plugin_message__field_indices_by_name[] = {
  1,   /* field[1] = invoke_request */
  2,   /* field[2] = property_get_request */
  3,   /* field[3] = property_set_request */
  0,   /* field[0] = registration_response */
};
static const ProtobufCIntRange blizzard__plugin__messages__manager_to_plugin_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor blizzard__plugin__messages__manager_to_plugin_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.plugin.messages.ManagerToPluginMessage",
  "ManagerToPluginMessage",
  "Blizzard__Plugin__Messages__ManagerToPluginMessage",
  "blizzard.plugin.messages",
  sizeof(Blizzard__Plugin__Messages__ManagerToPluginMessage),
  4,
  blizzard__plugin__messages__manager_to_plugin_message__field_descriptors,
  blizzard__plugin__messages__manager_to_plugin_message__field_indices_by_name,
  1,  blizzard__plugin__messages__manager_to_plugin_message__number_ranges,
  (ProtobufCMessageInit) blizzard__plugin__messages__manager_to_plugin_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__plugin__messages__registration_request__field_descriptors[1] =
{
  {
    "description",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Plugin__Messages__RegistrationRequest, description),
    &google__protobuf__any__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__plugin__messages__registration_request__field_indices_by_name[] = {
  0,   /* field[0] = description */
};
static const ProtobufCIntRange blizzard__plugin__messages__registration_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor blizzard__plugin__messages__registration_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.plugin.messages.RegistrationRequest",
  "RegistrationRequest",
  "Blizzard__Plugin__Messages__RegistrationRequest",
  "blizzard.plugin.messages",
  sizeof(Blizzard__Plugin__Messages__RegistrationRequest),
  1,
  blizzard__plugin__messages__registration_request__field_descriptors,
  blizzard__plugin__messages__registration_request__field_indices_by_name,
  1,  blizzard__plugin__messages__registration_request__number_ranges,
  (ProtobufCMessageInit) blizzard__plugin__messages__registration_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__plugin__messages__registration_response__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Plugin__Messages__RegistrationResponse, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__plugin__messages__registration_response__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange blizzard__plugin__messages__registration_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor blizzard__plugin__messages__registration_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.plugin.messages.RegistrationResponse",
  "RegistrationResponse",
  "Blizzard__Plugin__Messages__RegistrationResponse",
  "blizzard.plugin.messages",
  sizeof(Blizzard__Plugin__Messages__RegistrationResponse),
  1,
  blizzard__plugin__messages__registration_response__field_descriptors,
  blizzard__plugin__messages__registration_response__field_indices_by_name,
  1,  blizzard__plugin__messages__registration_response__number_ranges,
  (ProtobufCMessageInit) blizzard__plugin__messages__registration_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__plugin__messages__invoke_request__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Plugin__Messages__InvokeRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "method",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Plugin__Messages__InvokeRequest, method),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parameters",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Plugin__Messages__InvokeRequest, parameters),
    &google__protobuf__any__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__plugin__messages__invoke_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = method */
  2,   /* field[2] = parameters */
};
static const ProtobufCIntRange blizzard__plugin__messages__invoke_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor blizzard__plugin__messages__invoke_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.plugin.messages.InvokeRequest",
  "InvokeRequest",
  "Blizzard__Plugin__Messages__InvokeRequest",
  "blizzard.plugin.messages",
  sizeof(Blizzard__Plugin__Messages__InvokeRequest),
  3,
  blizzard__plugin__messages__invoke_request__field_descriptors,
  blizzard__plugin__messages__invoke_request__field_indices_by_name,
  1,  blizzard__plugin__messages__invoke_request__number_ranges,
  (ProtobufCMessageInit) blizzard__plugin__messages__invoke_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__plugin__messages__invoke_response__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Plugin__Messages__InvokeResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "success",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Plugin__Messages__InvokeResponse, status_case),
    offsetof(Blizzard__Plugin__Messages__InvokeResponse, success),
    &google__protobuf__any__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Blizzard__Plugin__Messages__InvokeResponse, status_case),
    offsetof(Blizzard__Plugin__Messages__InvokeResponse, error),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__plugin__messages__invoke_response__field_indices_by_name[] = {
  2,   /* field[2] = error */
  0,   /* field[0] = id */
  1,   /* field[1] = success */
};
static const ProtobufCIntRange blizzard__plugin__messages__invoke_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor blizzard__plugin__messages__invoke_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.plugin.messages.InvokeResponse",
  "InvokeResponse",
  "Blizzard__Plugin__Messages__InvokeResponse",
  "blizzard.plugin.messages",
  sizeof(Blizzard__Plugin__Messages__InvokeResponse),
  3,
  blizzard__plugin__messages__invoke_response__field_descriptors,
  blizzard__plugin__messages__invoke_response__field_indices_by_name,
  1,  blizzard__plugin__messages__invoke_response__number_ranges,
  (ProtobufCMessageInit) blizzard__plugin__messages__invoke_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__plugin__messages__property_get_request__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Plugin__Messages__PropertyGetRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "property",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Plugin__Messages__PropertyGetRequest, property),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__plugin__messages__property_get_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = property */
};
static const ProtobufCIntRange blizzard__plugin__messages__property_get_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor blizzard__plugin__messages__property_get_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.plugin.messages.PropertyGetRequest",
  "PropertyGetRequest",
  "Blizzard__Plugin__Messages__PropertyGetRequest",
  "blizzard.plugin.messages",
  sizeof(Blizzard__Plugin__Messages__PropertyGetRequest),
  2,
  blizzard__plugin__messages__property_get_request__field_descriptors,
  blizzard__plugin__messages__property_get_request__field_indices_by_name,
  1,  blizzard__plugin__messages__property_get_request__number_ranges,
  (ProtobufCMessageInit) blizzard__plugin__messages__property_get_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__plugin__messages__property_get_response__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Plugin__Messages__PropertyGetResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "success",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Plugin__Messages__PropertyGetResponse, status_case),
    offsetof(Blizzard__Plugin__Messages__PropertyGetResponse, success),
    &google__protobuf__any__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Blizzard__Plugin__Messages__PropertyGetResponse, status_case),
    offsetof(Blizzard__Plugin__Messages__PropertyGetResponse, error),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__plugin__messages__property_get_response__field_indices_by_name[] = {
  2,   /* field[2] = error */
  0,   /* field[0] = id */
  1,   /* field[1] = success */
};
static const ProtobufCIntRange blizzard__plugin__messages__property_get_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor blizzard__plugin__messages__property_get_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.plugin.messages.PropertyGetResponse",
  "PropertyGetResponse",
  "Blizzard__Plugin__Messages__PropertyGetResponse",
  "blizzard.plugin.messages",
  sizeof(Blizzard__Plugin__Messages__PropertyGetResponse),
  3,
  blizzard__plugin__messages__property_get_response__field_descriptors,
  blizzard__plugin__messages__property_get_response__field_indices_by_name,
  1,  blizzard__plugin__messages__property_get_response__number_ranges,
  (ProtobufCMessageInit) blizzard__plugin__messages__property_get_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__plugin__messages__property_set_request__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Plugin__Messages__PropertySetRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "property",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Plugin__Messages__PropertySetRequest, property),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Plugin__Messages__PropertySetRequest, value),
    &google__protobuf__any__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__plugin__messages__property_set_request__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = property */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange blizzard__plugin__messages__property_set_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor blizzard__plugin__messages__property_set_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.plugin.messages.PropertySetRequest",
  "PropertySetRequest",
  "Blizzard__Plugin__Messages__PropertySetRequest",
  "blizzard.plugin.messages",
  sizeof(Blizzard__Plugin__Messages__PropertySetRequest),
  3,
  blizzard__plugin__messages__property_set_request__field_descriptors,
  blizzard__plugin__messages__property_set_request__field_indices_by_name,
  1,  blizzard__plugin__messages__property_set_request__number_ranges,
  (ProtobufCMessageInit) blizzard__plugin__messages__property_set_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__plugin__messages__property_set_response__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Plugin__Messages__PropertySetResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "success",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Plugin__Messages__PropertySetResponse, status_case),
    offsetof(Blizzard__Plugin__Messages__PropertySetResponse, success),
    &google__protobuf__empty__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Blizzard__Plugin__Messages__PropertySetResponse, status_case),
    offsetof(Blizzard__Plugin__Messages__PropertySetResponse, error),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__plugin__messages__property_set_response__field_indices_by_name[] = {
  2,   /* field[2] = error */
  0,   /* field[0] = id */
  1,   /* field[1] = success */
};
static const ProtobufCIntRange blizzard__plugin__messages__property_set_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor blizzard__plugin__messages__property_set_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.plugin.messages.PropertySetResponse",
  "PropertySetResponse",
  "Blizzard__Plugin__Messages__PropertySetResponse",
  "blizzard.plugin.messages",
  sizeof(Blizzard__Plugin__Messages__PropertySetResponse),
  3,
  blizzard__plugin__messages__property_set_response__field_descriptors,
  blizzard__plugin__messages__property_set_response__field_indices_by_name,
  1,  blizzard__plugin__messages__property_set_response__number_ranges,
  (ProtobufCMessageInit) blizzard__plugin__messages__property_set_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__plugin__messages__event__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Plugin__Messages__Event, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Plugin__Messages__Event, value),
    &google__protobuf__any__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__plugin__messages__event__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange blizzard__plugin__messages__event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor blizzard__plugin__messages__event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.plugin.messages.Event",
  "Event",
  "Blizzard__Plugin__Messages__Event",
  "blizzard.plugin.messages",
  sizeof(Blizzard__Plugin__Messages__Event),
  2,
  blizzard__plugin__messages__event__field_descriptors,
  blizzard__plugin__messages__event__field_indices_by_name,
  1,  blizzard__plugin__messages__event__number_ranges,
  (ProtobufCMessageInit) blizzard__plugin__messages__event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
