/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: value.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "value.pb-c.h"
void   blizzard__value__value__init
                     (Blizzard__Value__Value         *message)
{
  static const Blizzard__Value__Value init_value = BLIZZARD__VALUE__VALUE__INIT;
  *message = init_value;
}
size_t blizzard__value__value__get_packed_size
                     (const Blizzard__Value__Value *message)
{
  assert(message->base.descriptor == &blizzard__value__value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__value__value__pack
                     (const Blizzard__Value__Value *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__value__value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__value__value__pack_to_buffer
                     (const Blizzard__Value__Value *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__value__value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Value__Value *
       blizzard__value__value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Value__Value *)
     protobuf_c_message_unpack (&blizzard__value__value__descriptor,
                                allocator, len, data);
}
void   blizzard__value__value__free_unpacked
                     (Blizzard__Value__Value *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__value__value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blizzard__value__list__init
                     (Blizzard__Value__List         *message)
{
  static const Blizzard__Value__List init_value = BLIZZARD__VALUE__LIST__INIT;
  *message = init_value;
}
size_t blizzard__value__list__get_packed_size
                     (const Blizzard__Value__List *message)
{
  assert(message->base.descriptor == &blizzard__value__list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__value__list__pack
                     (const Blizzard__Value__List *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__value__list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__value__list__pack_to_buffer
                     (const Blizzard__Value__List *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__value__list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Value__List *
       blizzard__value__list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Value__List *)
     protobuf_c_message_unpack (&blizzard__value__list__descriptor,
                                allocator, len, data);
}
void   blizzard__value__list__free_unpacked
                     (Blizzard__Value__List *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__value__list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blizzard__value__object__children_entry__init
                     (Blizzard__Value__Object__ChildrenEntry         *message)
{
  static const Blizzard__Value__Object__ChildrenEntry init_value = BLIZZARD__VALUE__OBJECT__CHILDREN_ENTRY__INIT;
  *message = init_value;
}
void   blizzard__value__object__init
                     (Blizzard__Value__Object         *message)
{
  static const Blizzard__Value__Object init_value = BLIZZARD__VALUE__OBJECT__INIT;
  *message = init_value;
}
size_t blizzard__value__object__get_packed_size
                     (const Blizzard__Value__Object *message)
{
  assert(message->base.descriptor == &blizzard__value__object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blizzard__value__object__pack
                     (const Blizzard__Value__Object *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blizzard__value__object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blizzard__value__object__pack_to_buffer
                     (const Blizzard__Value__Object *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blizzard__value__object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Blizzard__Value__Object *
       blizzard__value__object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Blizzard__Value__Object *)
     protobuf_c_message_unpack (&blizzard__value__object__descriptor,
                                allocator, len, data);
}
void   blizzard__value__object__free_unpacked
                     (Blizzard__Value__Object *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blizzard__value__object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor blizzard__value__value__field_descriptors[7] =
{
  {
    "boolean",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Blizzard__Value__Value, kind_case),
    offsetof(Blizzard__Value__Value, boolean),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "integer",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Blizzard__Value__Value, kind_case),
    offsetof(Blizzard__Value__Value, integer),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "double",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Blizzard__Value__Value, kind_case),
    offsetof(Blizzard__Value__Value, double_),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Blizzard__Value__Value, kind_case),
    offsetof(Blizzard__Value__Value, string),
    NULL,
    &protobuf_c_empty_string,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Blizzard__Value__Value, kind_case),
    offsetof(Blizzard__Value__Value, bytes),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "list",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Value__Value, kind_case),
    offsetof(Blizzard__Value__Value, list),
    &blizzard__value__list__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Value__Value, kind_case),
    offsetof(Blizzard__Value__Value, object),
    &blizzard__value__object__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__value__value__field_indices_by_name[] = {
  0,   /* field[0] = boolean */
  4,   /* field[4] = bytes */
  2,   /* field[2] = double */
  1,   /* field[1] = integer */
  5,   /* field[5] = list */
  6,   /* field[6] = object */
  3,   /* field[3] = string */
};
static const ProtobufCIntRange blizzard__value__value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor blizzard__value__value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.value.Value",
  "Value",
  "Blizzard__Value__Value",
  "blizzard.value",
  sizeof(Blizzard__Value__Value),
  7,
  blizzard__value__value__field_descriptors,
  blizzard__value__value__field_indices_by_name,
  1,  blizzard__value__value__number_ranges,
  (ProtobufCMessageInit) blizzard__value__value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__value__list__field_descriptors[1] =
{
  {
    "elements",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Value__List, n_elements),
    offsetof(Blizzard__Value__List, elements),
    &blizzard__value__value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__value__list__field_indices_by_name[] = {
  0,   /* field[0] = elements */
};
static const ProtobufCIntRange blizzard__value__list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor blizzard__value__list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.value.List",
  "List",
  "Blizzard__Value__List",
  "blizzard.value",
  sizeof(Blizzard__Value__List),
  1,
  blizzard__value__list__field_descriptors,
  blizzard__value__list__field_indices_by_name,
  1,  blizzard__value__list__number_ranges,
  (ProtobufCMessageInit) blizzard__value__list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__value__object__children_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Value__Object__ChildrenEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Blizzard__Value__Object__ChildrenEntry, value),
    &blizzard__value__value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__value__object__children_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange blizzard__value__object__children_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor blizzard__value__object__children_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.value.Object.ChildrenEntry",
  "ChildrenEntry",
  "Blizzard__Value__Object__ChildrenEntry",
  "blizzard.value",
  sizeof(Blizzard__Value__Object__ChildrenEntry),
  2,
  blizzard__value__object__children_entry__field_descriptors,
  blizzard__value__object__children_entry__field_indices_by_name,
  1,  blizzard__value__object__children_entry__number_ranges,
  (ProtobufCMessageInit) blizzard__value__object__children_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blizzard__value__object__field_descriptors[1] =
{
  {
    "children",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Blizzard__Value__Object, n_children),
    offsetof(Blizzard__Value__Object, children),
    &blizzard__value__object__children_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blizzard__value__object__field_indices_by_name[] = {
  0,   /* field[0] = children */
};
static const ProtobufCIntRange blizzard__value__object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor blizzard__value__object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "blizzard.value.Object",
  "Object",
  "Blizzard__Value__Object",
  "blizzard.value",
  sizeof(Blizzard__Value__Object),
  1,
  blizzard__value__object__field_descriptors,
  blizzard__value__object__field_indices_by_name,
  1,  blizzard__value__object__number_ranges,
  (ProtobufCMessageInit) blizzard__value__object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
