/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: value.proto */

#ifndef PROTOBUF_C_value_2eproto__INCLUDED
#define PROTOBUF_C_value_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Blizzard__Value__Value Blizzard__Value__Value;
typedef struct Blizzard__Value__List Blizzard__Value__List;
typedef struct Blizzard__Value__Object Blizzard__Value__Object;
typedef struct Blizzard__Value__Object__ChildrenEntry Blizzard__Value__Object__ChildrenEntry;


/* --- enums --- */


/* --- messages --- */

typedef enum {
  BLIZZARD__VALUE__VALUE__KIND__NOT_SET = 0,
  BLIZZARD__VALUE__VALUE__KIND_BOOLEAN = 1,
  BLIZZARD__VALUE__VALUE__KIND_INTEGER = 2,
  BLIZZARD__VALUE__VALUE__KIND_DOUBLE = 3,
  BLIZZARD__VALUE__VALUE__KIND_STRING = 4,
  BLIZZARD__VALUE__VALUE__KIND_BYTES = 5,
  BLIZZARD__VALUE__VALUE__KIND_LIST = 6,
  BLIZZARD__VALUE__VALUE__KIND_OBJECT = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BLIZZARD__VALUE__VALUE__KIND__CASE)
} Blizzard__Value__Value__KindCase;

struct  Blizzard__Value__Value
{
  ProtobufCMessage base;
  Blizzard__Value__Value__KindCase kind_case;
  union {
    ProtobufCBinaryData bytes;
    double double_;
    int64_t integer;
    char *string;
    Blizzard__Value__List *list;
    Blizzard__Value__Object *object;
    protobuf_c_boolean boolean;
  };
};
#define BLIZZARD__VALUE__VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__value__value__descriptor) \
, BLIZZARD__VALUE__VALUE__KIND__NOT_SET, { {0} } }


struct  Blizzard__Value__List
{
  ProtobufCMessage base;
  size_t n_elements;
  Blizzard__Value__Value **elements;
};
#define BLIZZARD__VALUE__LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__value__list__descriptor) \
, 0,NULL }


struct  Blizzard__Value__Object__ChildrenEntry
{
  ProtobufCMessage base;
  char *key;
  Blizzard__Value__Value *value;
};
#define BLIZZARD__VALUE__OBJECT__CHILDREN_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__value__object__children_entry__descriptor) \
, (char *)protobuf_c_empty_string, NULL }


struct  Blizzard__Value__Object
{
  ProtobufCMessage base;
  size_t n_children;
  Blizzard__Value__Object__ChildrenEntry **children;
};
#define BLIZZARD__VALUE__OBJECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&blizzard__value__object__descriptor) \
, 0,NULL }


/* Blizzard__Value__Value methods */
void   blizzard__value__value__init
                     (Blizzard__Value__Value         *message);
size_t blizzard__value__value__get_packed_size
                     (const Blizzard__Value__Value   *message);
size_t blizzard__value__value__pack
                     (const Blizzard__Value__Value   *message,
                      uint8_t             *out);
size_t blizzard__value__value__pack_to_buffer
                     (const Blizzard__Value__Value   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Value__Value *
       blizzard__value__value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__value__value__free_unpacked
                     (Blizzard__Value__Value *message,
                      ProtobufCAllocator *allocator);
/* Blizzard__Value__List methods */
void   blizzard__value__list__init
                     (Blizzard__Value__List         *message);
size_t blizzard__value__list__get_packed_size
                     (const Blizzard__Value__List   *message);
size_t blizzard__value__list__pack
                     (const Blizzard__Value__List   *message,
                      uint8_t             *out);
size_t blizzard__value__list__pack_to_buffer
                     (const Blizzard__Value__List   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Value__List *
       blizzard__value__list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__value__list__free_unpacked
                     (Blizzard__Value__List *message,
                      ProtobufCAllocator *allocator);
/* Blizzard__Value__Object__ChildrenEntry methods */
void   blizzard__value__object__children_entry__init
                     (Blizzard__Value__Object__ChildrenEntry         *message);
/* Blizzard__Value__Object methods */
void   blizzard__value__object__init
                     (Blizzard__Value__Object         *message);
size_t blizzard__value__object__get_packed_size
                     (const Blizzard__Value__Object   *message);
size_t blizzard__value__object__pack
                     (const Blizzard__Value__Object   *message,
                      uint8_t             *out);
size_t blizzard__value__object__pack_to_buffer
                     (const Blizzard__Value__Object   *message,
                      ProtobufCBuffer     *buffer);
Blizzard__Value__Object *
       blizzard__value__object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   blizzard__value__object__free_unpacked
                     (Blizzard__Value__Object *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Blizzard__Value__Value_Closure)
                 (const Blizzard__Value__Value *message,
                  void *closure_data);
typedef void (*Blizzard__Value__List_Closure)
                 (const Blizzard__Value__List *message,
                  void *closure_data);
typedef void (*Blizzard__Value__Object__ChildrenEntry_Closure)
                 (const Blizzard__Value__Object__ChildrenEntry *message,
                  void *closure_data);
typedef void (*Blizzard__Value__Object_Closure)
                 (const Blizzard__Value__Object *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor blizzard__value__value__descriptor;
extern const ProtobufCMessageDescriptor blizzard__value__list__descriptor;
extern const ProtobufCMessageDescriptor blizzard__value__object__descriptor;
extern const ProtobufCMessageDescriptor blizzard__value__object__children_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_value_2eproto__INCLUDED */
